### PR TITLE
fix: Add Server Service check to apply the changes in case the service exists

### LINKED ISSUE #1390: [argocd-operator.v0.9.1] : ArgoCD Server Options - Service.Type=NodePort not applied to service
**Describe the bug**
I tried modifying the service type of argocd-server from ClusterIP to NodePort.  After applying the manifest, the service type is still ClusterIP instead of NodePort.

Manifest used : 
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  server:
    service:
      type: NodePort

I was obliged to delete the service of the argocd-serve ClusterIP for it te be recreated with NodePort.

**To Reproduce**
1. After installing the operator : argocd-operator.v0.9.1, I applied the argocd-basic.yaml to deploy argocd.
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec: {}

2. Descriptions of deployment :
**kubectl get ArgoCD example-argocd -n argocd-ops-cb -o yaml**
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ArgoCD","metadata":{"annotations":{},"labels":{"example":"basic"},"name":"example-argocd","namespace":"argocd-ops-cb"},"spec":{}}
  creationTimestamp: "2024-05-29T13:35:05Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 1
  labels:
    example: basic
  name: example-argocd
  namespace: argocd-ops-cb
  resourceVersion: "130218573"
  uid: e8e23191-b09b-41ed-894a-e1514a18bb98
spec:
  controller:
    processors: {}
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac: {}
  redis: {}
  repo: {}
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
    service:
      type: ""
  tls:
    ca: {}
status:
  applicationController: Running
  applicationSetController: Unknown
  phase: Available
  redis: Running
  repo: Running
  server: Running
  sso: Unknown
**kubectl get deploy,ep,pods,svc -n argocd-ops-cb**
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-argocd-redis         1/1     1            1           55s
deployment.apps/example-argocd-repo-server   1/1     1            1           55s
deployment.apps/example-argocd-server        1/1     1            1           55s

NAME                                      ENDPOINTS                             AGE
endpoints/example-argocd-metrics          10.244.2.180:8082                     55s
endpoints/example-argocd-redis            10.244.1.134:6379                     55s
endpoints/example-argocd-repo-server      10.244.1.135:8084,10.244.1.135:8081   55s
endpoints/example-argocd-server           10.244.2.179:8080,10.244.2.179:8080   55s
endpoints/example-argocd-server-metrics   10.244.2.179:8083                     55s

NAME                                              READY   STATUS    RESTARTS   AGE
pod/example-argocd-application-controller-0       1/1     Running   0          55s
pod/example-argocd-redis-cd467b448-kq4gr          1/1     Running   0          55s
pod/example-argocd-repo-server-746db4d77c-gdrww   1/1     Running   0          55s
pod/example-argocd-server-65bc59648b-k4rbv        1/1     Running   0          55s

NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/example-argocd-metrics          ClusterIP   10.106.199.160   <none>        8082/TCP            55s
service/example-argocd-redis            ClusterIP   10.106.223.77    <none>        6379/TCP            55s
service/example-argocd-repo-server      ClusterIP   10.99.129.123    <none>        8081/TCP,8084/TCP   55s
service/example-argocd-server           ClusterIP   10.111.166.175   <none>        80/TCP,443/TCP      55s
service/example-argocd-server-metrics   ClusterIP   10.109.153.160   <none>        8083/TCP            55s

4. kubectl apply the following manifest to replace service type ClusterIP to NodePort 
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  server:
    service:
      type: NodePort

5. Descriptions of deployment :
**kubectl get ArgoCD example-argocd -n argocd-ops-cb -o yaml**
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ArgoCD","metadata":{"annotations":{},"labels":{"example":"basic"},"name":"example-argocd","namespace":"argocd-ops-cb"},"spec":{"server":{"service":{"type":"NodePort"}}}}
  creationTimestamp: "2024-05-29T13:35:05Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 2
  labels:
    example: basic
  name: example-argocd
  namespace: argocd-ops-cb
  resourceVersion: "130220119"
  uid: e8e23191-b09b-41ed-894a-e1514a18bb98
spec:
  controller:
    processors: {}
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac: {}
  redis: {}
  repo: {}
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
    service:
      type: NodePort
  tls:
    ca: {}
status:
  applicationController: Running
  applicationSetController: Unknown
  phase: Available
  redis: Running
  repo: Running
  server: Running
  sso: Unknown

**kubectl get deploy,ep,pods,svc -n argocd-ops-cb**
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-argocd-redis         1/1     1            1           5m40s
deployment.apps/example-argocd-repo-server   1/1     1            1           5m40s
deployment.apps/example-argocd-server        1/1     1            1           5m40s

NAME                                      ENDPOINTS                             AGE
endpoints/example-argocd-metrics          10.244.2.180:8082                     5m40s
endpoints/example-argocd-redis            10.244.1.134:6379                     5m40s
endpoints/example-argocd-repo-server      10.244.1.135:8084,10.244.1.135:8081   5m40s
endpoints/example-argocd-server           10.244.2.179:8080,10.244.2.179:8080   5m40s
endpoints/example-argocd-server-metrics   10.244.2.179:8083                     5m40s

NAME                                              READY   STATUS    RESTARTS   AGE
pod/example-argocd-application-controller-0       1/1     Running   0          5m40s
pod/example-argocd-redis-cd467b448-kq4gr          1/1     Running   0          5m40s
pod/example-argocd-repo-server-746db4d77c-gdrww   1/1     Running   0          5m40s
pod/example-argocd-server-65bc59648b-k4rbv        1/1     Running   0          5m40s

NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/example-argocd-metrics          ClusterIP   10.106.199.160   <none>        8082/TCP            5m40s
service/example-argocd-redis            ClusterIP   10.106.223.77    <none>        6379/TCP            5m40s
service/example-argocd-repo-server      ClusterIP   10.99.129.123    <none>        8081/TCP,8084/TCP   5m40s
service/example-argocd-server           ClusterIP   10.111.166.175   <none>        80/TCP,443/TCP      5m40s
service/example-argocd-server-metrics   ClusterIP   10.109.153.160   <none>        8083/TCP            5m40s

**The NodeIP wasn't applied**

6. Delete service/example-argocd-server  ClusterIP

**kubectl delete service/example-argocd-server -n argocd-ops-cb**
service "example-argocd-server" deleted

**kubectl get deploy,ep,pods,svc -n argocd-ops-cb**
NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-argocd-redis         1/1     1            1           7m28s
deployment.apps/example-argocd-repo-server   1/1     1            1           7m28s
deployment.apps/example-argocd-server        1/1     1            1           7m28s

NAME                                      ENDPOINTS                             AGE
endpoints/example-argocd-metrics          10.244.2.180:8082                     7m28s
endpoints/example-argocd-redis            10.244.1.134:6379                     7m28s
endpoints/example-argocd-repo-server      10.244.1.135:8084,10.244.1.135:8081   7m28s
endpoints/example-argocd-server           10.244.2.179:8080,10.244.2.179:8080   6s
endpoints/example-argocd-server-metrics   10.244.2.179:8083                     7m28s

NAME                                              READY   STATUS    RESTARTS   AGE
pod/example-argocd-application-controller-0       1/1     Running   0          7m28s
pod/example-argocd-redis-cd467b448-kq4gr          1/1     Running   0          7m28s
pod/example-argocd-repo-server-746db4d77c-gdrww   1/1     Running   0          7m28s
pod/example-argocd-server-65bc59648b-k4rbv        1/1     Running   0          7m28s

NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/example-argocd-metrics          ClusterIP   10.106.199.160   <none>        8082/TCP                     7m28s
service/example-argocd-redis            ClusterIP   10.106.223.77    <none>        6379/TCP                     7m28s
service/example-argocd-repo-server      ClusterIP   10.99.129.123    <none>        8081/TCP,8084/TCP            7m28s
service/example-argocd-server           NodePort    10.97.58.42      <none>        80:31514/TCP,443:30393/TCP   6s
service/example-argocd-server-metrics   ClusterIP   10.109.153.160   <none>        8083/TCP                     7m28s

**The NodeIP was applied after deleting the service**

**Expected behavior**
Since the desired stated for the server service type has changed (from ClusterIP to NodePort), this should be applied to the cluster automatically without deleting the ressource.

Thanks for your help. :)

### PR DESCRIPTION
**Pull request by nmirasch**
**What type of PR is this?**
 /kind bug 

**What does this PR do / why we need it**:
This PR adds logic to reconcile any manual changes on Server Service properties.

**Which issue(s) this PR fixes**:

Fixes #1390

**How to test changes / Special notes to the reviewer**:
I performed an upgrade test as follows:

1. Ran make run
2. Created an ArgoCD CR.
3. Check the Server Service Type is ClusterIP (by default)
4. Apply 
```yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: basic
spec:
  server:
    service:
      type: NodePort
```
6.Check the Server Service Type is NodePort

### CODE REVIEW

File: controllers/argocd/service.go [hunk 1]
```diff
@@ -461,6 +448,27 @@ func (r *ReconcileArgoCD) reconcileServerService(cr *argoproj.ArgoCD) error {
...
+		}
+		changed := false
+		if !reflect.DeepEqual(svc.Spec.Type, existingSVC.Spec.Type) {
+			changed = true
+		}
+		if changed {
+			return r.Client.Update(context.TODO(), svc)
+		}
+		return nil
+	}
```
Comment (svghadi) [inline controllers/argocd/service.go:471]:
```suggestion
		if !reflect.DeepEqual(svc.Spec.Type, existingSVC.Spec.Type) {
		        existingSVC.Spec.Type = svc.Spec.Type
			changed = true
		}
		if changed {
			return r.Client.Update(context.TODO(), existingSVC)
		}
		return nil  // no changes detected, do nothing
	}
```
While updating, we should prefer using existing resource obj `existingSVC` in `Update` with modified fields using data from our latest constructed source of truth obj i.e `svc`

File: controllers/argocd/service.go [hunk 2]
```diff
@@ -461,6 +448,27 @@ func (r *ReconcileArgoCD) reconcileServerService(cr *argoproj.ArgoCD) error {
...
+	if argoutil.IsObjectFound(r.Client, cr.Namespace, svc.Name, existingSVC) {
+		if !cr.Spec.Server.IsEnabled() {
+			return r.Client.Delete(context.TODO(), svc)
+		}
+		if ensureAutoTLSAnnotation(r.Client, svc, common.ArgoCDServerTLSSecretName, cr.Spec.Server.WantsAutoTLS()) {
+			return r.Client.Update(context.TODO(), svc)
+		}
+		if !cr.Spec.Repo.IsEnabled() {
+			return nil
+		}
```
Comment (svghadi) [inline controllers/argocd/service.go:462]:
```suggestion
		if !cr.Spec.Server.IsEnabled() {
			return nil
		}
```
Seems like there is an existing bug in this check. It should be `.Server` and not `.Repo`. This check is used to skip service creation for the server is it is disabled by setting `cr.spec.server.enabled: true` in `ArgoCD` CR. Let's also move this check out of update loop towards the end i.e before `Create` so that it correctly prevents the creation of service if  server is disabled.

**Review by svghadi — CHANGES_REQUESTED** [review]
Thanks @nmirasch. Left few suggestions.

**Review by svghadi — APPROVED** [review]

**Comment by svghadi** [comment]
Thanks @nmirasch. Congratulation on your first contribution :tada: .
