### PR TITLE
fix: Add update logic to handle addition of PSS to deployments

### LINKED ISSUE #1492: [v0.11.0] argocd-operator deployment fails with PodSecurity "restricted:latest", seccompProfile missing
**Describe the bug**

Deploying the argocd-operator fails in a Kubernetes cluster with the PodSecurity policy "restricted:latest" enabled. 
The error message indicates a violation due to the missing securityContext.seccompProfile.type in the manager container.

```
LAST SEEN   TYPE    REASON        OBJECT                                                   MESSAGE
4m35s       Warning FailedCreate  replicaset/argocd-operator-controller-manager-6855dff84f Error creating: pods "argocd-operator-controller-manager-6855dff84f-wmqrn" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or container "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**To Reproduce**
1. Apply Pod Security Standards restricted at [the Cluster Level](https://kubernetes.io/docs/tutorials/security/cluster-level-pss/) or at [ the Namespace](https://kubernetes.io/docs/tutorials/security/ns-level-pss/) where the operator is going to be installed
2. Follow the installation [documentation](https://argocd-operator.readthedocs.io/en/latest/install/olm/)

**Expected behavior**
argocd-operator should deploy successfully without violating the "restricted:latest" PodSecurity policy.

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**

> /kind bug

**What does this PR do / why we need it**:

[#1288](https://github.com/argoproj-labs/argocd-operator/pull/1288) and [#1493](https://github.com/argoproj-labs/argocd-operator/pull/1493) introduced Pod Security Standards (PSS) to ensure all Argo CD component pods comply with the restricted security policy. However, these changes only apply to new installations.

This PR addresses the gap by adding logic to update existing installations. It ensures that the necessary `securityContext` is applied to existing pods and automatically reconciles any manual changes back to the intended configuration.

**Which issue(s) this PR fixes**:

Closes #1492 

**How to test changes / Special notes to the reviewer**:

I performed an upgrade test as follows:
1. Ran `make run` with the `v0.11.0` tag.
2. Created an `ArgoCD` CR.
3. Stopped `make run` and switched to this `PR branch`.
4. Ran `make run` again.

The following command should return no warnings:
```bash
# Example of a non-compliant namespace
$ kubectl label --overwrite --dry-run=server ns test pod-security.kubernetes.io/enforce=restricted
Warning: existing pods in namespace "test" violate the new PodSecurity enforce level "restricted:latest"
namespace/test labeled (server dry run)

# Example of a compliant namespace
$ kubectl label --overwrite --dry-run=server ns test pod-security.kubernetes.io/enforce=restricted
namespace/test labeled (server dry run)
```

### CODE REVIEW

**Comment by saumeya** [comment]
Good solution for upgrade testing @svghadi

File: controllers/argocd/keycloak.go [hunk 1]
```diff
@@ -1515,3 +1514,18 @@ func (r *ReconcileArgoCD) reconcileKeycloak(cr *argoproj.ArgoCD) error {
 
 	return nil
 }
+
+func restrictedContainerSecurityContext() *corev1.SecurityContext {
```
Comment (saumeya) [inline controllers/argocd/keycloak.go:1518]: Why are we creating a function for security context only for keycloak resource?

Comment (svghadi) [reply controllers/argocd/keycloak.go:1518]: Actually, I wanted to create a common function for all deployments but realized that some have slightly different `securityContext` configurations. So to keep things simpler, didn't proceed with it. We can revisit this when we work on refactoring again.

**Review by saumeya — APPROVED** [review]
Tested with the upgrade scenario from 0.11 to this branch and works as expected.
LGTM 
Thanks @svghadi

**Comment by iam-veeramalla** [comment]
LGTM @svghadi, Thanks for the PR.
