### PR TITLE
fix: Reference Argo CD services by FQDN instead of short names

### LINKED ISSUE #262: Argo CD service names should be referenced by their FQDN
The Argo CD service names should be referenced by their FQDN in order to allow cluster-wide `no_proxy` settings to apply to all instances of Argo CD installed by the operator when a global proxy is set up.

So, instead of e.g. `--repo-server argocd-repo-server:8081`, the reference should be made as `--repo-server argocd-repo-server.<namespace>.svc.cluster.local` - this will also consider an already existing entry of `.cluster.local` in the `no_proxy` env var.

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #262

To discuss: Should the cluster domain suffix (e.g. `cluster.local`) be made configurable in the ArgoCD CR (or possibly, auto-detected).

@jgwest Since this also touches some of the recent AppSet integration, here's a FYI.

### CODE REVIEW

File: pkg/controller/argocd/deployment.go [hunk 1]
```diff
@@ -245,12 +239,12 @@ func getArgoServerCommand(cr *argoprojv1a1.ArgoCD) []string {
...
 // getDexServerAddress will return the Dex server address.
 func getDexServerAddress(cr *argoprojv1a1.ArgoCD) string {
-	return fmt.Sprintf("http://%s:%d", nameWithSuffix("dex-server", cr), common.ArgoCDDefaultDexHTTPPort)
+	return fmt.Sprintf("http://%s", fqdnServiceRef("dex-server", common.ArgoCDDefaultDexHTTPPort, cr))
 }
 
 // getRepoServerAddress will return the Argo CD repo server address.
 func getRepoServerAddress(cr *argoprojv1a1.ArgoCD) string {
-	return fmt.Sprintf("%s:%d", nameWithSuffix("repo-server", cr), common.ArgoCDDefaultRepoServerPort)
+	return fqdnServiceRef("repo-server", common.ArgoCDDefaultRepoServerPort, cr)
```
Comment (wtam2018) [inline pkg/controller/argocd/deployment.go:247]: I am not sure if the port is considered a part of the FQDN.

**Comment by wtam2018** [comment]
LGTM
@jannfis

**Comment by jannfis** [comment]
@wtam2018 I have end-to-end tested this locally, it works fine with FQDN service names.
