### PR TITLE
bug: fix redis fails after upgrade

### LINKED ISSUE #1804: ArgoCD Redis container fails with "runAsNonRoot and image will run as root" after upgrade to argocd-operator 0.14.1
**Description:**

After upgrading argocd-operator from version 0.13.1 to 0.14.1, the `argocd-redis` pod fails to start with the following error:

```
state:
  waiting:
    message: 'container has runAsNonRoot and image will run as root (pod: "argocd-redis-64656fd77c-5b58n_argocd(4433a4b7-dc74-4ab6-b270-5f47ce031643)", container: redis)'
    reason: CreateContainerConfigError
```

**Environment:**
- ArgoCD Operator version: 0.14.1 (previously 0.13.1)
- Kubernetes version: v1.32.4-gke.1698000
- Redis image: `redis@sha256:8061ca607db2a0c80010aeb5fc9bed0253448bc68711eaa14253a392f6c48280`

**Root Cause:**
The security context configuration changed between versions. The working configuration (v0.13.1) included:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 999  # This line is missing in v0.14.1
  seccompProfile:
    type: RuntimeDefault
```

The new configuration (v0.14.1) is missing the `runAsUser: 999` field:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true  # Without runAsUser, defaults to root (UID 0)
  seccompProfile:
    type: RuntimeDefault
```

**Expected Behavior:**
The Redis container should start successfully with the same security context as the previous version.

**Actual Behavior:**
The container fails to start because `runAsNonRoot: true` is specified but no `runAsUser` is set, causing the container to attempt running as root (UID 0), which violates the `runAsNonRoot` constraint.

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

/kind bug 

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #1804

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by svghadi** [comment]
@anandrkskd - is this ready for review?

File: controllers/argocd/deployment.go [hunk 1]
```diff
@@ -531,6 +525,10 @@ func (r *ReconcileArgoCD) reconcileRedisDeployment(cr *argoproj.ArgoCD, useTLS b
 		},
 	}}
 
+	if !IsOpenShiftCluster() {
+		deploy.Spec.Template.Spec.Containers[0].SecurityContext.RunAsUser = int64Ptr(999)
```
Comment (anandf) [inline controllers/argocd/deployment.go]: Is the change required because the init containers must not run as `999` user ?

**Comment by svghadi** [comment]
I was discussing this issue with @Mangaal. He suggested to add the missing update logic for `deploy.Spec.Template.Spec.SecurityContext` instead of dropping `1000` userid.  

Currently, the update logic only checks for  `SecurityContext` at container level, it should also check at template level in deployment
https://github.com/argoproj-labs/argocd-operator/blob/0882af31483c3779ea6dafa394db109eaede6ffd/controllers/argocd/deployment.go#L610-L617

File: controllers/argocd/deployment.go (hunk 1 above)
Comment (anandrkskd) [reply controllers/argocd/deployment.go]: Removed this part, pod Security context will now compare and update.
