### PR TITLE
[v0.4.x] fix: Keycloak/RHSSO login yields in certificate signed by unknown authority 

### LINKED ISSUE #761: Keycloak/RHSSO login yields in certificate signed by unknown authority
**Describe the bug**
Argo CD Operator can make use of RHSSO & KeyCloak through OIDC in addition to Dex. However, with a recent security fix applied, the certificate of RHSSO  or Keycloak cannot be validated in some scenarios. 

Single Sign On with Argo CD Operator can fail with the error message "x509: certificate signed by unknown authority" under the following circumstances:
```
    You are using RHSSO or KeyCloak as SSO provider and
    You are using a self-signed certificate for your route endpoints, or you are using a private CA to issue certificates
```

This behavior is a result of a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5) in Argo CD, which enforces a strict validation of TLS certificates on the configued OIDC endpoints.

### PR DESCRIPTION
**Pull request by iam-veeramalla**
**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
Single Sign On with GitOps Operator can fail with the error message "x509: certificate signed by unknown authority" under the following circumstances:

You are using RHSSO (KeyCloak) as SSO provider and You are using a self-signed certificate for your route endpoints, or you are using a private CA to issue certificates.

This behavior is a result of a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5) in Argo CD, which enforces a strict validation of TLS certificates on the configued OIDC endpoints.

**Workaround & Mitigation**
There are multiple workarounds available:
For Argo CD Operator 0.4.0, you can disable TLS validation for the OIDC (Keycloak/RHSSO) endpoint in the ArgoCD spec:
```
spec:
  extraConfig:
    oidc.tls.insecure.skip.verify: "true"
```

For Argo CD Operator 0.3.0 or less, you need to patch the `argocd-cm` ConfigMap in your instance's namespace as follows
```
oc patch configmap argocd-cm --patch='{"data": {"oidc.tls.insecure.skip.verify": "true"}}'
```

**Have you updated the necessary documentation?**
* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:
Fixes #761 
Closes #761 

**How to test changes / Special notes to the reviewer**:
1. Run the operator locally using `make install run`
2. Run the e2e test using `kubectl kuttl test ./tests/ocp --config ./tests/kuttl-tests.yaml --test 1-001_validate_rhsso`

(or)

3. You can also test this manually by
4. Create the Argo CD Instance using Keycloak as SSO provider.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: route
spec:
  sso:
    provider: keycloak
    keycloak:
       verifyTLS: false
       rootTLS: "--- Some Dummy Root CA ---"
  server:
    route:
      enabled: true
```
5. Give the operator 3-4 minutes to reconcile.
6. Verify that `rootCA` is added to the oidc.config in `argocd-cm` ConfigMap.
7. Modify the `rootCA` and verify that the operator reconciles the changes.

### CODE REVIEW

File: controllers/argocd/keycloak.go [hunk 1]
```diff
@@ -1404,49 +1409,56 @@ func (r *ReconcileArgoCD) reconcileKeycloakForOpenShift(cr *argoprojv1a1.ArgoCD)
...
+				}
 
-			if err != nil {
-				return err
-			}
+				// Update Realm creation. This will avoid posting of realm configuration on further reconciliations.
+				err = r.Client.Get(context.TODO(), types.NamespacedName{Name: existingDC.Name, Namespace: existingDC.Namespace}, existingDC)
+				if err != nil {
+					return err
+				}
```
Comment (jaideepr97) [inline controllers/argocd/keycloak.go:1440]: @iam-veeramalla any particular reason for introducing this get call here? seems like we would already have access to the existingDC resource after getting it on L 1381

Comment (iam-veeramalla) [reply controllers/argocd/keycloak.go:1440]: @jaideepr97 I did not make any changes to the existing code.

Comment (jaideepr97) [reply controllers/argocd/keycloak.go:1440]: That call has been added in this PR though, since it shows up in green

Comment (iam-veeramalla) [reply controllers/argocd/keycloak.go:1440]: Hey, its issue with git, please check the diff :)

**Review by jopit — APPROVED** [review]
LGTM
