### PR TITLE
fix: standardize logFormat field naming across ArgoCD components

### LINKED ISSUE #1821: Inconsistent logformat
**Describe the bug**
The logFormat option is inconsistently written between components. Some have logfomat, some have logFormat.

New options .spec.applicationSet.logformat and .spec.notifications.logformat were added in all lowercase.
But existing option .spec.controller.logFormat and in .spec.server.logFormat and .spec.repo.logFormat, were written with a capital 'F'.
This should be corrected to have argocd consistent options for logging: fieldnaming: logFormat

Looking at the desription (e.g. bundle/provided by oc explain, the description writes format with capital F.
So on that point there is more inconsistency.
(eg. config/crd/bases/argoproj.io_argocds.yaml about at line 1483)

So, were the latest 'logformat' field additions particularly written like that, or was it sloppy work?
 
**To Reproduce**
1. oc explain argocd.spec.applicationSet -> logformat
2. adding .spec.applicationSet.logformat works (but the field is inconsistent with logFormat from other argocd components., 
3. adding .spec.applicationSet.logformat does NOT work

**Expected behavior**
logFormat should be written the same in all components.

**Screenshots**
Extract from oc explain argocd:
  applicationSet	<Object>
    logformat	<string>         --> added in 1.17, 'f' should be 'F'
  controller	<Object>
    logFormat	<string>
  notifications	<Object>
    logformat	<string>         --> added in 1.17, 'f' should be 'F'
  repo	<Object>
    logFormat	<string>
  server	<Object>
    logFormat	<string>

**Additional context**
Having consistent fieldnames.

### PR DESCRIPTION
**Pull request by tzprograms**
**What type of PR is this?**

/kind bug

## What does this PR do / Why we need it

This PR fixes an inconsistency in logging configuration field naming across ArgoCD components.

The fields:
- `.spec.applicationSet.logformat`
- `.spec.notifications.logformat`

were introduced in lowercase, while other components already use camelCase:

- `.spec.controller.logFormat`
- `.spec.server.logFormat`
- `.spec.repo.logFormat`

This change standardizes the field naming to `logFormat` to maintain consistency across all ArgoCD components.

## Changes

- Updated Go struct JSON tags
- Regenerated CRDs (`make manifests`)
- Regenerated bundle (`make bundle`)

## Which issue(s) this PR fixes

Fixes  #1821

## How to test changes

1. Install the updated CRD.
2. Verify the schema using:
  -`oc explain argocd.spec.applicationSet.logFormat`
  -`oc explain argocd.spec.notifications.logFormat`

3. Confirm that lowercase fields no longer exist:
  -`oc explain argocd.spec.applicationSet.logformat`
  -`oc explain argocd.spec.notifications.logformat`
  Expected result: lowercase fields should not exist.

## Summary by CodeRabbit

* **Bug Fixes**
  * Restored backward-compatible log format handling and corrected JSON key casing (adds deprecated alias).

* **New Features**
  * Added a consolidated SSO configuration block for unified authentication provider setup.

* **Chores**
  * Standardized log-related field names, descriptions and ordering across schemas.
  * Added schema validation to disallow simultaneous SSO and OIDC config.
  * Updated operator metadata/display text, reduced one RBAC permission, and minor test formatting tweaks.

### CODE REVIEW

File: api/v1alpha1/argocd_types.go [hunk 1]
```diff
@@ -349,7 +349,7 @@ type ArgoCDNotifications struct {
 
 	// LogFormat refers to the log format used by the argocd-notifications. Defaults to ArgoCDDefaultLogFormat if not configured. Valid options are text or json.
 	// +kubebuilder:validation:Enum=text;json
-	LogFormat string `json:"logformat,omitempty"`
+	LogFormat string `json:"logFormat,omitempty"`
```
[the remark this answers is not in the document]
Comment (tzprograms) [reply api/v1alpha1/argocd_types.go:355]: The goal of this change was to standardize the field naming across ArgoCD components as described in #1821.

I'm happy to add a backward-compatibility fallback for the legacy `logformat` key if maintainers think it's necessary.

File: bundle/manifests/argocd-operator.clusterserviceversion.yaml [hunk 2]
```diff
@@ -257,13 +257,13 @@ metadata:
...
-    createdAt: "2026-02-27T08:39:33Z"
+    createdAt: "2026-03-04T02:57:35Z"
     description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.
     operators.operatorframework.io/builder: operator-sdk-v1.35.0
     operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
     repository: https://github.com/argoproj-labs/argocd-operator
     support: Argo CD
-  name: argocd-operator.v0.19.0
+  name: argocd-operator.v0.18.0
   namespace: placeholder
```
[the remark this answers is not in the document]
Comment (tzprograms) [reply bundle/manifests/argocd-operator.clusterserviceversion.yaml]: The CSV and catalog files were regenerated using `make bundle` after rebasing on the latest upstream `master` , and I did not intentionally modify version or replacement metadata.

If the bundle needs to be regenerated differently or aligned with the current release version in the repository, I’m happy to update it accordingly.

File: deploy/olm-catalog/argocd-operator/0.18.0/argocd-operator.v0.18.0.clusterserviceversion.yaml [hunk 3]
```diff
@@ -424,7 +424,7 @@ spec:
       specDescriptors:
       - description: ApplicationInstanceLabelKey is the key name where Argo CD injects
           the app name as a tracking label.
-        displayName: Application Instance Label Key
+        displayName: Application Instance Label Key'
```
[the remark this answers is not in the document]
Comment (tzprograms) [reply deploy/olm-catalog/argocd-operator/0.18.0/argocd-operator.v0.18.0.clusterserviceversion.yaml]: The bundle and catalog manifests were regenerated using `make bundle`, so these `displayName` entries were not modified manually.

If the descriptors should be adjusted in the source annotations or regenerated with a different tool version, I’m happy to update them.

**Comment by svghadi** [comment]
Hi @tzprograms , thank you for working on this. We need to take care of a few things to ensure smooth upgrades:

1. Renaming the `logformat` field directly in the API/CRD could result in a breaking change. The recommended approach is to introduce the new field `logFormat` and deprecate the existing field. The deprecated field can then be removed in a future release when we bump the `apiVersion`.
3. The reconciliation logic also needs to be updated to consider both fields, i.e., `logformat` and `logFormat`, with the latter taking higher priority. This will ensure that users already using the old field do not run into issues during upgrades, while new users can start using the new field.
5. This could also be handled via a conversion webhook, where the operator moves the value from the old field to the new field automatically. However, this would require a CRD version bump and could be considered in a future release.

**Comment by tzprograms** [comment]
Thank you for the review @svghadi , I will take a look at them as soon as possible.

File: api/v1beta1/argocd_types.go [hunk 4]
```diff
@@ -217,9 +217,12 @@ type ArgoCDApplicationSet struct {
 	// VolumeMounts adds volumeMounts to the Argo CD ApplicationSet Controller container.
 	VolumeMounts []corev1.VolumeMount `json:"volumeMounts,omitempty"`
 
+	// Deprecated: use LogFormat instead.
+	Logformat string `json:"logformat,omitempty"`
+
 	// LogFormat refers to the log format used by the ApplicationSet component. Defaults to ArgoCDDefaultLogFormat if not configured. Valid options are text or json.
 	// +kubebuilder:validation:Enum=text;json
-	LogFormat string `json:"logformat,omitempty"`
+	LogFormat string `json:"logFormat,omitempty"`
```
Comment (anandf) [inline api/v1beta1/argocd_types.go:225]: Can we add a tag for setting the default 
```
    // +kubebuilder:validation:Enum=text;json
    // +kubebuilder:default:=json
```

File: controllers/argocd/applicationset.go [hunk 5]
```diff
@@ -61,8 +61,15 @@ func (r *ReconcileArgoCD) getArgoApplicationSetCommand(cr *argoproj.ArgoCD) []st
 	cmd = append(cmd, "--loglevel")
 	cmd = append(cmd, getLogLevel(cr.Spec.ApplicationSet.LogLevel))
 
+	// Higher Preference to the new logFormat field. Fall back to the deprecated logformat field for backward compatibility.
+	logFormat := cr.Spec.ApplicationSet.LogFormat
+	if logFormat == "" {
```
Comment (anandf) [inline controllers/argocd/applicationset.go:67]: if we set a default value, this may not be empty. To handle backward compatibility, can we use conversion webhook to convert any `logformat` customer has set to `logFormat`. If that is not possible, then we can have this code and not set any default value.

File: controllers/argocd/applicationset.go [hunk 6]
```diff
@@ -61,8 +61,15 @@ func (r *ReconcileArgoCD) getArgoApplicationSetCommand(cr *argoproj.ArgoCD) []st
...
+		//nolint:staticcheck // fallback to deprecated field for backward compatibility
```
Comment (anandf) [inline controllers/argocd/applicationset.go:68]: Why is `nolint` required ? does the linter complain about anything ?

File: controllers/argocd/applicationset.go (hunk 5 above)
Comment (svghadi) [reply controllers/argocd/applicationset.go:67]: I think we can implement this change in the next CRD version bump, since conversion webhooks cannot handle changes within the same CRD version.

File: api/v1beta1/argocd_types.go (hunk 4 above)
Comment (svghadi) [reply api/v1beta1/argocd_types.go:225]: Maybe we can set a default in the next API version. Doing it in the same version might cause backward compatibility issues, since conversion webhooks can’t handle this within the same API version.

**Review by svghadi — CHANGES_REQUESTED** [review]
Can we add some unit and e2e tests?

**Review by svghadi — APPROVED** [review]
LGTM. Thanks @tzprograms

**Comment by anandf** [comment]
LGTM, resolve the conflicts reported in this PR to be able to merge the changes.

**Review by anandf — APPROVED** [review]

File: deploy/olm-catalog/argocd-operator/0.18.0/argocd-operator.v0.18.0.clusterserviceversion.yaml
Comment (svghadi) [inline deploy/olm-catalog/argocd-operator/0.18.0/argocd-operator.v0.18.0.clusterserviceversion.yaml:1]: Lets revert the changes from 0.18.0 files

File: deploy/olm-catalog/argocd-operator/0.18.0/argoproj.io_argocds.yaml
Comment (svghadi) [inline deploy/olm-catalog/argocd-operator/0.18.0/argoproj.io_argocds.yaml:1]: Same as previous comment

**Review by svghadi — APPROVED** [review]

**Comment by svghadi** [comment]
Thank you -  @tzprograms 

and thanks @anandf for the review
