### PR TITLE
fix: upgrade ingress to networking/v1

### LINKED ISSUE #420: Operator projects using the removed APIs in k8s 1.22 requires changes.
### Problem Description

Kubernetes has been deprecating API(s), which will be removed and are no longer available in 1.22. Operators projects using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) versions will **not** work on Kubernetes 1.22 or any cluster vendor using this Kubernetes version(1.22), such as OpenShift 4.9+. Following the APIs that are most likely your projects to be affected by:
- apiextensions.k8s.io/v1beta1: (Used for CRDs and available since v1.16)
- rbac.authorization.k8s.io/v1beta1: (Used for RBAC/rules and available since v1.8)
- admissionregistration.k8s.io/v1beta1 (Used for Webhooks and available since v1.16)

Therefore, looks like this project distributes solutions in the [repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/argocd-operator) and does not contain any version compatible with k8s 1.22/OCP 4.9. ([More info](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138)). Following some findings by checking the distributions published:

- **argocd-operator.v0.0.13**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.14**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.15**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.5**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.8**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.9**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.12**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.4**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.6**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 
- **argocd-operator.v0.0.11**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["applications.argoproj.io" "appprojects.argoproj.io" "argocdexports.argoproj.io" "argocds.argoproj.io"]) 

**NOTE:** The above findings are only about the manifests shipped inside of the distribution. It is not checking the codebase.

### How to solve

It would be very nice to see new distributions of this project that are no longer using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) and so they can work on Kubernetes 1.22 and newer and published in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/argocd-operator) collection. OpenShift 4.9, for example, will not ship operators anymore that do still use v1beta1 extension APIs.

Due to the number of options available to build Operators, it is hard to provide direct guidance on updating your operator to support Kubernetes 1.22. Recent versions of the [OperatorSDK](https://github.com/operator-framework/operator-sdk) greater than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) and [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) greater than [3.0.0](https://github.com/kubernetes-sigs/kubebuilder/releases) scaffold your project with the latest versions of these APIs (all that is generated by tools only). See the guides to upgrade your projects with OperatorSDK [Golang](https://sdk.operatorframework.io/docs/building-operators/golang/migration/), [Ansible](https://sdk.operatorframework.io/docs/building-operators/ansible/migration/), [Helm](https://sdk.operatorframework.io/docs/building-operators/helm/migration/) or the [Kubebuilder](https://book.kubebuilder.io/migration/v2vsv3.html) one. For APIs other than the ones mentioned above, you will have to check your code for usage of removed API versions and upgrade to newer APIs. The details of this depend on your codebase.

**If this projects only need to migrate the API for CRDs and it was built with [OperatorSDK](https://github.com/operator-framework/operator-sdk) versions lower than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) then, you maybe able to solve it with an [OperatorSDK](https://github.com/operator-framework/operator-sdk) version >= v0.18.x < 1.0.0:**

> $ operator-sdk generate crds --crd-version=v1
> INFO[0000] Running CRD generator.                       
> INFO[0000] CRD generation complete.

**Alternatively, you can try to upgrade your manifests with [controller-gen](https://book.kubebuilder.io/reference/controller-gen.html) ([version >= v0.4.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.1)) :**

#### If this project does not use Webhooks:

> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role  paths="./..."

#### If this project is using Webhooks:

1. Add the markers [sideEffects](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L81) and [admissionReviewVersions](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L114) to your webhook (Example with sideEffects=None and admissionReviewVersions={v1,v1beta1}: [memcached-operator/api/v1alpha1/memcached_webhook.go](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go#L39)):

2. Run the command:
> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths="./..."

For further information and tips see the [comment](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138#discussioncomment-1245759).

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
/kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
Upgrades ingress resource from ```extensions/v1beta1``` to ```networking.k8s.io/v1``` in order to make it compatible with k8s v1.22 

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #420 #390

**How to test changes / Special notes to the reviewer**:
Run ```make test``` for unit tests, for e2e tests, have 2 separate terminals running. Execute ``` ARGOCD_CLUSTER_CONFIG_NAMESPACES=argocd-e2e-cluster-config make install run``` in 1, followed by ```hack/test.sh``` in the other

### CODE REVIEW

**Comment by jaideepr97** [comment]
cc @iam-veeramalla @jopit @jannfis

**Comment by iam-veeramalla** [comment]
> cc @iam-veeramalla @jopit @jannfis @wtam2018

@jaideepr97  Please let me know when this is ready for review. I would like to run some ingress tests to verify the changes.

File: controllers/argocd/ingress.go [hunk 1]
```diff
@@ -18,16 +18,17 @@ import (
...
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
-	"k8s.io/apimachinery/pkg/util/intstr"
 	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
 
 	argoprojv1a1 "github.com/argoproj-labs/argocd-operator/api/v1alpha1"
 	"github.com/argoproj-labs/argocd-operator/common"
 	"github.com/argoproj-labs/argocd-operator/controllers/argoutil"
 )
 
+var PathTypeImplementationSpecific = networkingv1.PathTypeImplementationSpecific
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:30]: Can you use this networkingv1.PathTypeImplementationSpecific const directly instead of assigning to a var?

File: bundle/manifests/argoproj.io_argocds.yaml [hunk 2]
```diff
@@ -260,14 +260,15 @@ spec:
                               items:
                                 type: string
                               type: array
+                              x-kubernetes-list-type: atomic
                             secretName:
                               description: SecretName is the name of the secret used
-                                to terminate SSL traffic on 443. Field is left optional
```
Comment (wtam2018) [inline bundle/manifests/argoproj.io_argocds.yaml:265]: I wonder where this change is coming from?

File: controllers/argocd/ingress.go (hunk 1 above)
Comment (jaideepr97) [reply controllers/argocd/ingress.go:30]: Since it's a constant the compiler throws an error when I try to reference it directly because go doesn't allow accessing the address of a constsnt, so I had workaround it

File: bundle/manifests/argoproj.io_argocds.yaml (hunk 2 above)
Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml:265]: These mostly likely came from when I ran ```make manifests``` from a different version of operator-sdk than what was used for the code in master 

I wasn't sure about what it's impact would be so I left it in to be reviewed but I can undo these

File: api/v1alpha1/zz_generated.deepcopy.go [hunk 3]
```diff
@@ -24,7 +24,7 @@ import (
 	routev1 "github.com/openshift/api/route/v1"
 	autoscalingv1 "k8s.io/api/autoscaling/v1"
 	"k8s.io/api/core/v1"
-	"k8s.io/api/extensions/v1beta1"
+	networkingv1 "k8s.io/api/networking/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	runtime "k8s.io/apimachinery/pkg/runtime"
```
Comment (wtam2018) [inline api/v1alpha1/zz_generated.deepcopy.go:29]: It looks like there is spacing difference between edited code and generated code.   Run `make` and  this file is re-generated with differences.  
image

File: controllers/argocd/ingress.go (hunk 1 above)
Comment (wtam2018) [inline controllers/argocd/ingress.go:30]:
```suggestion
```

File: controllers/argocd/ingress.go [hunk 4]
```diff
@@ -120,18 +121,23 @@ func (r *ReconcileArgoCD) reconcileArgoServerIngress(cr *argoprojv1a1.ArgoCD) er
 	ingress.ObjectMeta.Annotations = atns
 
 	// Add rules
-	ingress.Spec.Rules = []extv1beta1.IngressRule{
+	ingress.Spec.Rules = []networkingv1.IngressRule{
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:124]:
```suggestion
	pathType := networkingv1.PathTypeImplementationSpecific
	ingress.Spec.Rules = []networkingv1.IngressRule{
```

File: controllers/argocd/ingress.go [hunk 5]
```diff
@@ -120,18 +121,23 @@ func (r *ReconcileArgoCD) reconcileArgoServerIngress(cr *argoprojv1a1.ArgoCD) er
...
-								ServicePort: intstr.FromString("http"),
+							Backend: networkingv1.IngressBackend{
+								Service: &networkingv1.IngressServiceBackend{
+									Name: nameWithSuffix("server", cr),
+									Port: networkingv1.ServiceBackendPort{
+										Name: "http",
+									},
+								},
 							},
+							PathType: &PathTypeImplementationSpecific,
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:140]:
```suggestion
							PathType: &pathType,
```

File: controllers/argocd/ingress.go [hunk 6]
```diff
@@ -187,18 +193,23 @@ func (r *ReconcileArgoCD) reconcileArgoServerGRPCIngress(cr *argoprojv1a1.ArgoCD
 	ingress.ObjectMeta.Annotations = atns
 
 	// Add rules
-	ingress.Spec.Rules = []extv1beta1.IngressRule{
+	ingress.Spec.Rules = []networkingv1.IngressRule{
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:196]:
```suggestion
	pathType := networkingv1.PathTypeImplementationSpecific
	ingress.Spec.Rules = []networkingv1.IngressRule{
```

File: controllers/argocd/ingress.go [hunk 7]
```diff
@@ -187,18 +193,23 @@ func (r *ReconcileArgoCD) reconcileArgoServerGRPCIngress(cr *argoprojv1a1.ArgoCD
...
-								ServicePort: intstr.FromString("https"),
+							Backend: networkingv1.IngressBackend{
+								Service: &networkingv1.IngressServiceBackend{
+									Name: nameWithSuffix("server", cr),
+									Port: networkingv1.ServiceBackendPort{
+										Name: "https",
+									},
+								},
 							},
+							PathType: &PathTypeImplementationSpecific,
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:212]:
```suggestion
							PathType: &pathType,
```

File: controllers/argocd/ingress.go [hunk 8]
```diff
@@ -207,7 +218,7 @@ func (r *ReconcileArgoCD) reconcileArgoServerGRPCIngress(cr *argoprojv1a1.ArgoCD
 	}
 
 	// Add TLS options
-	ingress.Spec.TLS = []extv1beta1.IngressTLS{
+	ingress.Spec.TLS = []networkingv1.IngressTLS{
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:221]:
```suggestion
	pathType := networkingv1.PathTypeImplementationSpecific
	ingress.Spec.TLS = []networkingv1.IngressTLS{
```

File: controllers/argocd/ingress.go [hunk 9]
```diff
@@ -255,18 +266,23 @@ func (r *ReconcileArgoCD) reconcileGrafanaIngress(cr *argoprojv1a1.ArgoCD) error
...
-								ServicePort: intstr.FromString("http"),
+							Backend: networkingv1.IngressBackend{
+								Service: &networkingv1.IngressServiceBackend{
+									Name: nameWithSuffix("grafana", cr),
+									Port: networkingv1.ServiceBackendPort{
+										Name: "http",
+									},
+								},
 							},
+							PathType: &PathTypeImplementationSpecific,
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:285]:
```suggestion
							PathType: &pathType,
```

File: controllers/argocd/ingress.go [hunk 10]
```diff
@@ -275,7 +291,7 @@ func (r *ReconcileArgoCD) reconcileGrafanaIngress(cr *argoprojv1a1.ArgoCD) error
 	}
 
 	// Add TLS options
-	ingress.Spec.TLS = []extv1beta1.IngressTLS{
+	ingress.Spec.TLS = []networkingv1.IngressTLS{
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:294]:
```suggestion
	pathType := networkingv1.PathTypeImplementationSpecific
	ingress.Spec.TLS = []networkingv1.IngressTLS{
```

File: controllers/argocd/ingress.go [hunk 11]
```diff
@@ -324,18 +340,23 @@ func (r *ReconcileArgoCD) reconcilePrometheusIngress(cr *argoprojv1a1.ArgoCD) er
...
-								ServicePort: intstr.FromString("web"),
+							Backend: networkingv1.IngressBackend{
+								Service: &networkingv1.IngressServiceBackend{
+									Name: "prometheus-operated",
+									Port: networkingv1.ServiceBackendPort{
+										Name: "web",
+									},
+								},
 							},
+							PathType: &PathTypeImplementationSpecific,
```
Comment (wtam2018) [inline controllers/argocd/ingress.go:359]:
```suggestion
							PathType: &pathType,
```

File: bundle/manifests/argoproj.io_argocds.yaml (hunk 2 above)
Comment (jannfis) [reply bundle/manifests/argoproj.io_argocds.yaml:265]: > when I ran make manifests using a different version of operator-sdk

I think this is generally a bad idea. The Operator SDK version used for development must match the one used in the corresponding branch.

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml:265]: Yeah, understood 
I think John mentioned he's going to generate manifests again with v1. 11.0 so I can do the same now, along with the other changes

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml:276]: I've reverted the changes to the argocd CRD, but for some reason it isn't reflecting in the changed files view of the PR

**Review by jannfis — APPROVED** [review]
LGTM, thanks @jaideepr97 !

**Comment by iam-veeramalla** [comment]
Verified the basic work flow with ingress SSL offloading and it works fine.
LGTM !!

**Comment by iam-veeramalla** [comment]
Please take a look at this before merging 
https://github.com/argoproj-labs/argocd-operator/pull/428#discussion_r704519289

File: bundle/manifests/argoproj.io_argocds.yaml (hunk 2 above)
Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml]: Do we want to do it in this PR? I thought John was working on generating manifests with v1.11.0 in a different PR

Comment (jopit) [reply bundle/manifests/argoproj.io_argocds.yaml]: The update to v1.11.0 has already been merged: https://github.com/argoproj-labs/argocd-operator/pull/429.

Comment (jopit) [reply bundle/manifests/argoproj.io_argocds.yaml]: @iam-veeramalla @jaideepr97 are you on mac or linux?  I'm on mac. I don't see these changes when running `make manifests` on Jaideep's branch.  If Abhishek is seeing these changes when running `make manifests` on this branch, then something weird is going on and I'm wondering if it's related to the OS.

`make manifests` calls `bin/controller-gen`, which is downloaded by the Makefile, and should be at version 0.6.1 regardless of which operator-sdk version is being used.

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml]: I'm confused, when I use 1.11.0 locally I also see these changes being made
however, when I look at what's in master I don't see these changes  and they aren't showing up in the diff here either

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml]: I'm on linux @jopit

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml]: I feel like as the Gitops team, we should just look at git as the source of truth here :sweat_smile: 
if the git diff with master looks okay then I guess we  can be sure this won't be introducing anything unwanted into master regardless of what's happening on our local machines?

Comment (jopit) [reply bundle/manifests/argoproj.io_argocds.yaml]: OK, I must have got confused somehow.  When I run `make manifests` on Jaideep's GITOPS-1304-upgrade-ingress branch, I do indeed see the changes getting made.  When I run it on master, I don't.

**However** it seems this change is due to changing `k8s.io/api/extensions/v1beta1` to `k8s.io/api/networking/v1` in `argocd_types.go`.  If I make the same change to `argocd_types.go` in my master branch, I see the change in the CRD.

So this change **should* be committed.

Comment (jopit) [reply bundle/manifests/argoproj.io_argocds.yaml]: I think the important part of the change is this
```
                                   type: array
+                                  x-kubernetes-list-type: atomic
                                 secretName:
```

Comment (jaideepr97) [reply bundle/manifests/argoproj.io_argocds.yaml]: @jopit Do you know if these changes should go in `config > crd > bases> argoproj.io_argocds.yaml` or `bundle > manifests > argoproj.io_argocds.yaml` or both? Because earlier I was seeing them in the bundle, but now I'm only seeing them under config

Comment (jopit) [reply bundle/manifests/argoproj.io_argocds.yaml]: `make bundle` needs to be rerun to regenerate the files under the bundle folder

**Comment by jopit** [comment]
LGTM

File: bundle/manifests/argoproj.io_argocds.yaml (hunk 2 above)
Comment (wtam2018) [reply bundle/manifests/argoproj.io_argocds.yaml:276]: @jaideepr97 We do need to understand how the change was introduced.

**Review by wtam2018 — APPROVED** [review]
