### PR TITLE
fix: Update sso eventing logic to stop spam

### LINKED ISSUE #785: Deprecation warning event spamming and incomplete association with operand
**Describe the bug**
Currently the operator spams deprecation warning events on the cluster when any of the soon-to-be-deprecated SSO/dex related fields/env vars are used. There are too many events being generated and they aren't timestamped or properly associated with the affected CR 

**To Reproduce**

Install/run the operator and have a CR using the old SSO config method or specifying the `DISABLE_DEX` env var in the subscription

**Expected behavior**
A single event is generated with proper timestamps and CR association, and its count updated if multiple occurances of the event are observed, instead of spamming events and polluting the cluster 

**Screenshots**

**Additional context**
https://issues.redhat.com/browse/GITOPS-2230

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

 /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
This PR updates the logic for SSO related field deprecations in the CR, so that single event is emitted with latest timestamp and CR association so that no. of emitted events is greatly reduced and events have more metadata stored

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #785 
https://issues.redhat.com/browse/GITOPS-2230

**How to test changes / Special notes to the reviewer**:

1. Run the operator against a cluster
2. Create an argo-cd instance and add `.spec.dex.config: test-config` 
3. run `kubectl get events` against that namespace
4. Only single occurrence of deprecation notice event should be present

### CODE REVIEW

File: controllers/argoutil/resource.go [hunk 1]
```diff
@@ -52,17 +52,23 @@ func CombineImageTag(img string, tag string) string {
 }
 
 // CreateEvent will create a new Kubernetes Event with the given action, message, reason and involved uid.
-func CreateEvent(client client.Client, eventType, action, message, reason string, meta metav1.ObjectMeta) error {
-	event := newEvent(meta)
+func CreateEvent(client client.Client, eventType, action, message, reason string, ObjectMeta metav1.ObjectMeta, typeMeta metav1.TypeMeta) error {
```
Comment (jopit) [inline controllers/argoutil/resource.go:55]: I'm curious why the `ObjectMeta` parameter name starts with an uppercase letter?

File: controllers/argocd/sso.go [hunk 2]
```diff
@@ -68,31 +72,42 @@ func (r *ReconcileArgoCD) reconcileSSO(cr *argoprojv1a1.ArgoCD) error {
...
 	}
 
 	if cr.Spec.SSO != nil && (cr.Spec.SSO.Image != "" || cr.Spec.SSO.Version != "" ||
 		cr.Spec.SSO.VerifyTLS != nil || cr.Spec.SSO.Resources != nil) {
 
-		// Emit event warning users about deprecation notice for `.spec.SSO` field users
-		err := argoutil.CreateEvent(r.Client, "Warning", "Deprecated", "`.spec.SSO.Image`, `.spec.SSO.Version`, `.spec.SSO.Resources` and `.spec.SSO.VerifyTLS` are deprecated, and support will be removed in Argo CD Operator v0.6.0/OpenShift GitOps v1.9.0. Keycloak configuration can be managed through `.spec.sso.keycloak`", "DeprecationNotice", cr.ObjectMeta)
-		if err != nil {
-			return err
+		// Emit event warning users about deprecation notice for `.spec.dex` users if not emitted already
```
[the remark this answers is not in the document]
Comment (jaideepr97) [reply controllers/argocd/sso.go]: updated, thanks

File: controllers/argoutil/resource.go (hunk 1 above)
Comment (jaideepr97) [reply controllers/argoutil/resource.go]: no particular reason
changed it, thanks

**Review by jopit — APPROVED** [review]
LGTM
