### PR TITLE
fix: panic when missing init containers

### LINKED ISSUE #586: Panic due to missing init container
**Describe the bug**

PR #562 introduced a bug where a panic occurs if a version of Argo CD is installed on the cluster by an older version of the operator that didn't have the CMP 2.0 support included.

```
panic: runtime error: index out of range [0] with length 0

goroutine 505 [running]:
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileRepoDeployment(0xc000ac2d20, 0xc0007b5800)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/deployment.go:1060 +0x2773
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileDeployments(0x27e1e80, 0xc0003e1640)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/deployment.go:347 +0x6c
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileResources(0xc000ac2d20, 0xc0007b5800)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/util.go:755 +0x2a7
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).Reconcile(0xc000ac2d20, {0x27c5cf8, 0xc0008883c0}, {{{0xc0005ff0b9, 0x24aa140}, {0xc000b06930, 0x30}}})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/argocd_controller.go:122 +0x42e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00023c580, {0x27c5cf8, 0xc0008882d0}, {{{0xc0005ff0b9, 0x24aa140}, {0xc000b06930, 0x1014f54}}})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00023c580, {0x27c5c50, 0xc0005cd6c0}, {0x23cffe0, 0xc000b40b00})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00023c580, {0x27c5c50, 0xc0005cd6c0})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357```

### PR DESCRIPTION
**Pull request by jopit**
Signed-off-by: John Pitman <jpitman@redhat.com>

**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:

Fixes a bug with CMP 2.0 support where the reconciler would panic if there was an existing argocd repo deployment without any init containers

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #586

**How to test**

* Install the operator.
* Install an Argo CD instance
* Edit the repo server deployment and delete the init container
  `kubectl edit deployments.apps argocd-repo-server `
* The operator should not panic. Edit the repo server deployment again and check that the init container was added back

### CODE REVIEW

File: controllers/argocd/deployment.go [hunk 1]
```diff
@@ -1056,6 +1056,10 @@ func (r *ReconcileArgoCD) reconcileRepoDeployment(cr *argoprojv1a1.ArgoCD) error
 				deploy.Spec.Template.Spec.Containers[1:]...)
 			changed = true
 		}
+		if !reflect.DeepEqual(deploy.Spec.Template.Spec.InitContainers, existing.Spec.Template.Spec.InitContainers) {
```
Comment (wtam2018) [inline controllers/argocd/deployment.go:1059]: The desired InitContainers are in `deploy.Spec.Template.Spec.InitContainers`. Doing this here should be enough, right?  Do we need line 1063 - 1080 (copying volumne monnts, env, resources, command to the first initContainer)?

**Comment by iam-veeramalla** [comment]
@jopit @wtam2018 I can reproduce this error even without a pre-existing Argo CD instance.

1. On my minikube cluster(new cluster), I ran the operator locally using `make install run`.
2. Create an Argo CD instance as below.
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd-keycloak
  labels:
    example: keycloak
spec:
  server:
    ingress: 
      enabled: true
```

Wait for a minute or 2 for the operator to panic with below error.
```
panic: runtime error: index out of range [0] with length 0

goroutine 553 [running]:
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileRepoDeployment(0xc0008b81c0, 0xc000f0a000)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/deployment.go:1060 +0x2773
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileDeployments(0x27e1e80, 0xc0000f39c0)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/deployment.go:347 +0x6c
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).reconcileResources(0xc0008b81c0, 0xc000f0a000)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/util.go:755 +0x2a7
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).Reconcile(0xc0008b81c0, {0x27c5cf8, 0xc0006c86c0}, {{{0xc0008a2b70, 0x24aa140}, {0xc0008a2b58, 0x30}}})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/argocd_controller.go:122 +0x42e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0008e80b0, {0x27c5cf8, 0xc0006c8600}, {{{0xc0008a2b70, 0x24aa140}, {0xc0008a2b58, 0x1014f54}}})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008e80b0, {0x27c5c50, 0xc00081dc40}, {0x23cffe0, 0xc00094d360})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008e80b0, {0x27c5c50, 0xc00081dc40})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x357
exit status 2
make: *** [run] Error 1
```

**Review by wtam2018 — APPROVED** [review]
LGTM
