### PR TITLE
fix: operator when run locally fails to create ArgoCD to manage cluster resources for OpenShift

### LINKED ISSUE #339: operator when run locally fails to create Argo CD to manage cluster scoped resources for OpenShift cluster
**Describe the bug**
This bug is very specific to openshift.

Operator when run locally fails to create Argo CD to manage cluster scoped resources. Below error can be seen in the error logs continuously.

```
{"level":"error","ts":1623844239.269036,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"argocd-controller","request":"openshift-gitops/openshift-gitops","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/aveerama/go/src/github.com/iam-veeramalla/gitops-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.
```

**Expected behavior**
operator should not thrown any error and create workloads to manage cluster config resources.

**Screenshots**
```
{"level":"error","ts":1623844239.269036,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"argocd-controller","request":"openshift-gitops/openshift-gitops","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/aveerama/go/src/github.com/iam-veeramalla/gitops-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.
```

**Additional context**
Error seems to be introduced as part of :
https://github.com/argoproj-labs/argocd-operator/blob/fcf1972d725e4b7422609de0582636710d75a16e/pkg/reconciler/openshift/openshift.go#L71

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Note: This bug is very specific to OpenShift

**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
fixes #339 

**Have you updated the necessary documentation?**
NA

Fixes #?
#339 

**How to test changes / Special notes to the reviewer**:
1. Run the operator locally
2. Create an ArgoCD instance to manage cluster config resource.

### CODE REVIEW

File: pkg/reconciler/openshift/openshift.go [hunk 1]
```diff
@@ -67,12 +69,14 @@ func reconcilerHook(cr *argoprojv1alpha1.ArgoCD, v interface{}, hint string) err
 	case *rbacv1.Role:
 		if o.ObjectMeta.Name == cr.Name+"-"+"argocd-application-controller" {
 			logv.Info("configuring policy rule for Application Controller")
+
 			// can move this to somewhere common eventually, maybe init()
 			k8sClient, err := initK8sClient()
 			if err != nil {
-				logv.Error(err, "failed to initialise kube client")
+				logv.Error(err, "failed to initialize kube client")
```
Comment (shubhamagarwal19) [inline pkg/reconciler/openshift/openshift.go:76]: We are already logging the error here, so maybe within the function, we can avoid logging the error so that we don't log the same error twice? (L350 and L356)

File: pkg/reconciler/openshift/openshift.go [hunk 2]
```diff
@@ -2,18 +2,19 @@ package openshift
 
 import (
 	"context"
-	"k8s.io/client-go/kubernetes"
 	"os"
 	"strings"
 
+	"k8s.io/client-go/kubernetes"
```
Comment (jannfis) [inline pkg/reconciler/openshift/openshift.go:8]: :+1:

File: pkg/reconciler/openshift/openshift.go (hunk 1 above)
Comment (jannfis) [inline pkg/reconciler/openshift/openshift.go:76]: :+1:

**Review by jannfis — APPROVED** [review]
LGTM, thanks @iam-veeramalla !

File: pkg/reconciler/openshift/openshift.go (hunk 1 above)
Comment (iam-veeramalla) [reply pkg/reconciler/openshift/openshift.go:75]: nice catch shubham :) , Thanks

**Review by shubhamagarwal19 — APPROVED** [review]
LGTM, Thanks !!
