### PR TITLE
fix: host url for Ingress in the .status feild on OpenShift (#)

### LINKED ISSUE #816: Argo CD .status.host is updated with wrong value when using Ingress on OpenShift clusters
**Describe the bug**

Argo CD .status.host is updated with wrong value when using Ingress on OpenShift clusters

`Openshift 4.11`
==================

Create test-namespace 'test-ns'

**Create Argo CD instance with the manifest** 
```
    apiVersion: argoproj.io/v1alpha1    
    kind: ArgoCD    
    metadata:      
      name: example-argocd      
      namespace: test-ns
      labels:        
        example: ingress    
    spec:      
      server:        
        host: example-argocd.<apps_domain_name>
        grpc:          
          ingress:            
            enabled: true        
        ingress:          
          enabled: true          
          tls:          
          - hosts:              
            - example-argocd        
        insecure: true
```

**Actual results:**

The ingress is created and it's getting Argo CD's .spec.server.host as HOSTS (.spec.rules[0].host):

```
NAME                    CLASS    HOSTS                                                    ADDRESS                                             
example-argocd-server   <none>   example-argocd.apps.rjeczkowaws-411z.ocp-gitops-qe.com   router-default.apps.rjeczkowaws-411z.ocp-gitops-qe.com 
```

**$ oc get ingress/example-argocd-server -o jsonpath="{.spec.rules[0].host}" -n test-ns**
`example-argocd.apps.rjeczkowaws-411z.ocp-gitops-qe.com`

_Argo CD on .status.host field is updated with `router-default.apps.xxxxxxx-411.ocp-xxxx-xx.com` which is the same as Ingress ADDRESS (`.status.loadBalancer.ingress[0].hostname`)._

**$ oc get argocd -o jsonpath="{.items[*]['status.host']}" -n test-ns**
`router-default.apps.rjeczkowaws-411z.ocp-gitops-qe.com`

$ oc get ingress/example-argocd-server -o jsonpath="{.status.loadBalancer.ingress[0].hostname}" -n test-ns
router-default.apps.rjeczkowaws-411z.ocp-gitops-qe.com

**Expected behavior**

Argo CD should copy the value of Ingress .spec.rules[0].host (instead of .status.loadBalancer.ingress[0].hostname) to .status.host because that's the URL of Argo CD.

**Screenshots**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
Fixes #816 
Closes #816 

**How to test changes / Special notes to the reviewer**:
Refer #816 

**Additionally you can also run the newly added automation tests on your OCP platform**
- `kubectl kuttl test ./tests/ocp --config ./tests/kuttl-tests.yaml --test 1-002_verify_hostname_with_ingress`
-  `kubectl kuttl test ./tests/ocp --config ./tests/kuttl-tests.yaml --test 1-003_verify_hostname_with_route`

### CODE REVIEW

File: controllers/argocd/status.go [hunk 1]
```diff
@@ -250,16 +253,41 @@ func (r *ReconcileArgoCD) reconcileStatusNotifications(cr *argoprojv1a1.ArgoCD)
...
-			return nil
-		}
+
+	// Log an error if a user configures route on a platform where route API does not exist.
+	// This is a misconfiguration.
+	if cr.Spec.Server.Route.Enabled && !IsRouteAPIAvailable() {
+		err := errors.New("Misconfiguration:")
+		log.Error(err, "Routes not available in non-OpenShift environments, please use Ingresses instead")
+		return nil
+	}
```
Comment (jaideepr97) [inline controllers/argocd/status.go:263]: @iam-veeramalla Any specific reason the code for this check is placed here? Seems like https://github.com/argoproj-labs/argocd-operator/blob/master/controllers/argocd/route.go#L217 might be a better place for it

**Review by jaideepr97 — APPROVED** [review]
LGTM, thanks @iam-veeramalla !
